version: '3.8'

services:
  # 1. Сервис Базы Данных MSSQL
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: django_mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD} # Задайте сложный пароль
    ports:
      - "1433:1433" # Открываем порт наружу, чтобы вы могли подключиться через SQL Management Studio
    volumes:
      - mssql_data:/var/opt/mssql
#Сервис Django
  web:
    build: .
    container_name: django_web_app
    command: gunicorn django_erbu.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=host.docker.internal  # Для связи Docker -> Windows
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway" # <-- Разрешаем этот адрес внутри Linux

  # 3. Сервис Веб-сервера Nginx
  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80" # Пробрасываем стандартный веб-порт на ваш компьютер/сервер
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  mssql_data:    # Сохраняет данные БД на вашем жестком диске, чтобы они не удалялись при перезапуске
  static_volume: # Общая папка для статики между Django и Nginx
  media_volume:  # Общая папка для медиа-файлов